export const LOGOUT = 'LOGOUT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const GET_TASKS_SUCCESS = 'GET_TASKS_SUCCESS';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';
export const UPDATE_TASK_SUCCESS = 'UPDATE_TASK_SUCCESS';
